# PostgresSQL.  Versions 8.2 recommended.
#
# Fedora Install Instructions:
#   sudo yum install ruby-postgres postgresql-server
#   sudo /sbin/service postgresql initdb
#   sudo /sbin/service postgresql start
#   sudo su - postgres
#   $   createdb polisher
#   $   psql polisher
#   $-# CREATE USER polisher WITH PASSWORD 'polisher';
#   $-# CREATE DATABASE polisher_development;
#   $-# GRANT ALL PRIVILEGES ON DATABASE polisher_development to polisher;
#   $-# CREATE DATABASE polisher_test;
#   $-# GRANT ALL PRIVILEGES ON DATABASE polisher_test to polisher;
#   $-# CREATE DATABASE polisher;
#   $-# GRANT ALL PRIVILEGES ON DATABASE polisher to polisher;
#   $-# \q
#   $   exit
#   rake db:migrate
#
#   On a local system you may need to edit this file to have only the following
#   /var/lib/pgsql/data/pg_hba.conf
#   local all all trust
#   host all all 127.0.0.1 255.255.255.255 trust


development:
  adapter: postgresql
  database: polisher
  username: polisher
  password: polisher
  host: localhost

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: polisher
  username: polisher
  host: localhost

production:
  adapter: postgresql
  database: polisher
  username: polisher
  password: polisher
  host: localhost
