# polisher database configuration

production:
  adapter: sqlite3
  database:  db/data/polisher.sqlite

development:
  adapter: sqlite3
  database:  db/data/polisher-development.sqlite

test:
  adapter: sqlite3
  database:  db/data/polisher-test.sqlite
