development:
  gem_api_key:       "YOUR GEMCUTTER API KEY HERE"
  email_from:        "foo@example.host"
  email_server:      "localhost"
  email_subject:     "gem #{gem_name} updated"
  email_body:        "gem #{gem_name} updated"

test:
  gem_api_key:       "YOUR GEMCUTTER API KEY HERE"
  email_from:        "foo@example.host"
  email_server:      "localhost"
  email_subject:     "gem #{gem_name} updated"
  email_body:        "gem #{gem_name} updated"

production:
  gem_api_key:       "YOUR GEMCUTTER API KEY HERE"
  email_from:        "foo@example.host"
  email_server:      "localhost"
  email_subject:     "gem #{gem_name} updated"
  email_body:        "gem #{gem_name} updated"
